parameters:
#    brix_admin.example.class: Brix\AdminBundle\Example

services:
    app.cors_listener:
        class: Brix\AdminBundle\Listener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#    brix_admin.example:
#        class: %brix_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
